services:
  api:
    build:
      context: .
      dockerfile: /src/Services/Main/Main.Web/DockerfileDev
    ports:
      - 5000:5000
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - "/app/Main.Web/bin"
      - "/app/Main.Web/obj"
      - "/app/Main.Application/bin"
      - "/app/Main.Application/obj"
      - "/app/Main.Infrastructure/bin"
      - "/app/Main.Infrastructure/obj"
      - './src/Services/Main/Main.Web/:/app/Main.Web'
      - './src/Services/Main/Main.Application/:/app/Main.Application'
      - './src/Services/Main/Main.Infrastructure/:/app/Main.Infrastructure'
      - './src/Services/Main/Main.Tools/:/app/Main.Tools'
    depends_on:
      - postgres

  front:
    build:
      context: ./src/Web/react-app/
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - WATCHPACK_POLLING=true
    volumes:
      - ./src/Web/react-app:/app
      - "/app/node_modules"
    depends_on:
      - api

  postgres:
    image: postgres:14.5
    environment:
      POSTGRES_DB: "dekoffeeDb"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "pass"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - 5432:5432
