services:
  api:
    build:
      context: ./Services/Main/
      dockerfile: Main.Web/DockerfileDev
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - "/app/Main.Web/bin"
      - "/app/Main.Web/obj"
      - "/app/Main.Application/bin"
      - "/app/Main.Application/obj"
      - "/app/Main.Infrastructure/bin"
      - "/app/Main.Infrastructure/obj"
      - './Services/Main/Main.Web/:/app/Main.Web'
      - './Services/Main/Main.Application/:/app/Main.Application'
      - './Services/Main/Main.Infrastructure/:/app/Main.Infrastructure'
      - './Services/Main/Main.Tools/:/app/Main.Tools'
    depends_on:
      - postgres

  postgres:
    image: postgres:14.5
    environment:
      POSTGRES_DB: "dekoffeeDb"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "pass"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"

name: dekoffee